In [1]:
import os

from google.cloud import bigquery

HTTP_PROXY = 'http://sia-lb.telekom.de:8080'
HTTPS_PROXY = 'http://sia-lb.telekom.de:8080'

os.environ['http_proxy'] = HTTP_PROXY
os.environ['https_proxy'] = HTTPS_PROXY

# --- 1. Initialize BigQuery client ---
PROJECT_ID = 'athlete-dashboard-467718'
DATASET_ID = 'strava_data_overview'
TABLE_ID = 'activities_strava'
# client = bigquery.Client(project=PROJECT_ID)
client = bigquery.Client.from_service_account_json(
    'C:/Users/A200162055/Downloads/athlete-dashboard-467718-d5f31b294e6f.json',
    project='athlete-dashboard-467718',
)
print('BigQuery verbunden!')

full_table_id = f'{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}'

# --- 4. Prüfen, ob Tabelle existiert ---
table = client.get_table(full_table_id)
print(f'ℹ️ Tabelle gefunden: {full_table_id}')
print(f'Spalten: {[schema.name for schema in table.schema]}')
print(f'Zeilen: {table.num_rows}')

# --- 5. Kleine Abfrage, um Daten zu testen ---
query = f'SELECT * FROM `{full_table_id}`'
print('🔹 Starte Abfrage:', query)

job = client.query(query)
df = job.result().to_dataframe()  # Ergebnisse in Pandas DataFrame

print('✅ Abfrage abgeschlossen, erste Zeilen:')
df

C:\Users\A200162055\Miniconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

BigQuery verbunden!
ℹ️ Tabelle gefunden: athlete-dashboard-467718.strava_data_overview.activities_strava
Spalten: ['resource_state', 'name', 'distance', 'moving_time', 'elapsed_time', 'total_elevation_gain', 'type', 'sport_type', 'workout_type', 'id', 'start_date', 'start_date_local', 'timezone', 'utc_offset', 'location_city', 'location_state', 'location_country', 'achievement_count', 'kudos_count', 'comment_count', 'athlete_count', 'photo_count', 'trainer', 'commute', 'manual', 'private', 'visibility', 'flagged', 'gear_id', 'start_latlng', 'end_latlng', 'average_speed', 'max_speed', 'average_cadence', 'average_watts', 'max_watts', 'weighted_average_watts', 'device_watts', 'kilojoules', 'has_heartrate', 'average_heartrate', 'max_heartrate', 'heartrate_opt_out', 'display_hide_heartrate_option', 'elev_high', 'elev_low', 'upload_id', 'upload_id_str', 'external_id', 'from_accepted_tag', 'pr_count', 'total_photo_count', 'has_kudoed', 'athlete_id', 'athlete_resource_state', 'map_id', 'map_summary_polyline', 'map_resource_state']
Zeilen: 194
🔹 Starte Abfrage: SELECT * FROM `athlete-dashboard-467718.strava_data_overview.activities_strava`

C:\Users\A200162055\Miniconda3\lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

✅ Abfrage abgeschlossen, erste Zeilen:

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,athlete_id,athlete_resource_state,map_id,map_summary_polyline,map_resource_state
0,2,First 100k,100376.0,14606,15953,1206.0,Ride,Ride,10.0,15287917307,...,garmin_ping_464391433871,False,11,0,False,133094316,1,a15287917307,waluH_q|j@rN`EnCbJoi@n}AqPjjA{L`g@cGfBkJqKeE}@...,2
1,2,Lunch Ride,28020.8,4337,4577,471.0,Ride,Ride,10.0,15240044605,...,garmin_ping_462951484937,False,3,0,False,133094316,1,a15240044605,}bluHcq}j@|BkFF{@mAcP[iCiEiOOsAc@}V@mBb@eDl@}H...,2
2,2,Ride,21328.7,2992,3173,249.0,Ride,Ride,10.0,15207390157,...,garmin_ping_461945757335,False,3,0,False,133094316,1,a15207390157,{bluHgq}j@vBeFHg@?k@o@eIq@_Hw@qDqCyJQoAg@}WBiB...,2
3,2,Lunch Ride,17796.5,1957,1957,99.0,Ride,Ride,10.0,15152957108,...,garmin_ping_460262900659,False,16,0,False,133094316,1,a15152957108,gbluHiq|j@~A\~@^bBd@~BXPFdAh@bAp@^`@Vl@FX`@tBJ...,2
4,2,Afternoon Ride,40195.1,5385,5820,430.0,Ride,Ride,10.0,15144808606,...,garmin_ping_459997785098,False,20,0,False,133094316,1,a15144808606,kiluHgg|j@@vBOlBnBt@?`@a@fEaA~CkAtFUrDj@~J|@dF...,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,2,Recovery Run,6527.8,2113,2113,51.0,Run,Run,0.0,14107411954,...,garmin_ping_426822647172,False,0,0,False,133094316,1,a14107411954,geluHym|j@F`DDX?bAIr@QnDMh@It@Cx@KjAG^_@x@gAlD...,2
190,2,Afternoon Run,6523.0,1764,1781,49.0,Run,Run,0.0,14068704800,...,garmin_ping_425536605510,False,0,0,False,133094316,1,a14068704800,geluHsm|j@D~BDx@?d@OnD[zBCv@KpA[fB_@tAa@|@St@s...,2
191,2,Afternoon Run,6525.8,2120,2124,54.0,Run,Run,0.0,14022373398,...,garmin_ping_423928634119,False,0,0,False,133094316,1,a14022373398,keluHym|j@FjBDlCEXIjA?b@G\QrBQtCQt@Qd@Ov@u@nBS...,2
192,2,Interval Run,5251.1,1415,1415,37.0,Run,Run,0.0,14000553784,...,garmin_ping_423167332404,False,0,0,False,133094316,1,a14000553784,meluH_o|j@BjAJx@Br@E~AG~@AbAK`BGPId@EdAOrBERQd...,2
193,2,Morning Run,6499.3,1955,1955,52.0,Run,Run,0.0,13950848663,...,garmin_ping_421595722901,False,0,0,False,133094316,1,a13950848663,keluHeo|j@NpFE`BCVEvAQpAG`BOlBKj@g@pAOl@k@dBS`...,2

In [33]:
unimportant_columns = [
    'resource_state',
    'location_city',
    'location_state',
    'location_country',
    'manual',
    'commute',
    'private',
    'visibility',
    'flagged',
    'start_latlng',
    'end_latlng',
    'heartrate_opt_out',
    'external_id',
    'upload_id',
    'upload_id_str',
    'from_accepted_tag',
    'has_kudoed',
    'athlete_resource_state',
    'map_resource_state',
]
df = df.drop(columns=unimportant_columns, errors='ignore')
df

,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,start_date,...,average_heartrate,max_heartrate,display_hide_heartrate_option,elev_high,elev_low,pr_count,total_photo_count,athlete_id,map_id,map_summary_polyline
0,First 100k,100376.0,14606,15953,1206.0,Ride,Ride,10.0,15287917307,2025-07-30T11:29:54Z,...,137.2,175.0,True,296.2,56.0,11,0,133094316,a15287917307,waluH_q|j@rN`EnCbJoi@n}AqPjjA{L`g@cGfBkJqKeE}@...
1,Lunch Ride,28020.8,4337,4577,471.0,Ride,Ride,10.0,15240044605,2025-07-26T09:03:05Z,...,133.9,164.0,True,215.0,61.0,3,0,133094316,a15240044605,}bluHcq}j@|BkFF{@mAcP[iCiEiOOsAc@}V@mBb@eDl@}H...
2,Ride,21328.7,2992,3173,249.0,Ride,Ride,10.0,15207390157,2025-07-23T08:48:13Z,...,138.2,169.0,True,216.0,68.8,3,0,133094316,a15207390157,{bluHgq}j@vBeFHg@?k@o@eIq@_Hw@qDqCyJQoAg@}WBiB...
3,Lunch Ride,17796.5,1957,1957,99.0,Ride,Ride,10.0,15152957108,2025-07-18T09:20:29Z,...,167.0,180.0,True,117.0,62.4,16,0,133094316,a15152957108,gbluHiq|j@~A\~@^bBd@~BXPFdAh@bAp@^`@Vl@FX`@tBJ...
4,Afternoon Ride,40195.1,5385,5820,430.0,Ride,Ride,10.0,15144808606,2025-07-17T12:41:07Z,...,149.7,179.0,True,221.2,65.4,20,0,133094316,a15144808606,kiluHgg|j@@vBOlBnBt@?`@a@fEaA~CkAtFUrDj@~J|@dF...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Recovery Run,6527.8,2113,2113,51.0,Run,Run,0.0,14107411954,2025-04-07T14:52:12Z,...,139.1,155.0,True,113.2,95.2,0,0,133094316,a14107411954,geluHym|j@F`DDX?bAIr@QnDMh@It@Cx@KjAG^_@x@gAlD...
190,Afternoon Run,6523.0,1764,1781,49.0,Run,Run,0.0,14068704800,2025-04-03T14:07:44Z,...,157.3,169.0,True,122.8,104.6,0,0,133094316,a14068704800,geluHsm|j@D~BDx@?d@OnD[zBCv@KpA[fB_@tAa@|@St@s...
191,Afternoon Run,6525.8,2120,2124,54.0,Run,Run,0.0,14022373398,2025-03-29T16:36:28Z,...,142.7,160.0,True,111.2,92.4,0,0,133094316,a14022373398,keluHym|j@FjBDlCEXIjA?b@G\QrBQtCQt@Qd@Ov@u@nBS...
192,Interval Run,5251.1,1415,1415,37.0,Run,Run,0.0,14000553784,2025-03-27T10:22:08Z,...,156.0,173.0,True,116.6,99.6,0,0,133094316,a14000553784,meluH_o|j@BjAJx@Br@E~AG~@AbAK`BGPId@EdAOrBERQd...
193,Morning Run,6499.3,1955,1955,52.0,Run,Run,0.0,13950848663,2025-03-22T06:52:34Z,...,146.9,164.0,True,117.8,100.8,0,0,133094316,a13950848663,keluHeo|j@NpFE`BCVEvAQpAG`BOlBKj@g@pAOl@k@dBS`...

In [31]:
df['athlete_count'].unique()

<IntegerArray>
[1, 2]
Length: 2, dtype: Int64

In [32]:
df[df['athlete_count'] == 2]

,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,start_date,...,average_heartrate,max_heartrate,display_hide_heartrate_option,elev_high,elev_low,pr_count,total_photo_count,athlete_id,map_id,map_summary_polyline
62,Afternoon Run,7566.0,2451,2539,39.5,Run,Run,0.0,12945501786,2024-11-20T16:39:21Z,...,154.6,188.0,True,107.5,90.0,0,0,133094316,a12945501786,ibopHef_s@VjEJ|@@XEj@@ZVvBFZBlBb@xD^bBt@bCIXU`...
65,Saturday Run,7772.5,2512,2531,61.9,Run,Run,0.0,12748074315,2024-10-26T11:10:20Z,...,156.9,175.0,True,118.6,90.2,0,0,133094316,a12748074315,aeluHek|j@BVCj@@nCOdBKj@Ej@Ax@EpA?h@CZKd@c@jAO...
118,Morning Run,4560.2,1497,1528,24.0,Run,Run,0.0,13305253341,2025-01-09T06:17:35Z,...,146.6,183.0,True,106.4,94.4,0,0,133094316,a13305253341,iwxpHqyat@SVE@]f@q@hAMXc@j@i@`AMPWf@[`@OXeAxAG...
119,Morning Run,6079.5,1857,1889,10.0,Run,Run,0.0,13287520377,2025-01-07T07:01:18Z,...,143.6,171.0,True,101.2,93.2,0,0,133094316,a13287520377,iwxpHsyat@Yj@_@\g@t@[j@e@n@[l@}AhCgAxASAE@]~@I...
120,Morning Run,6045.2,1872,1886,6.0,Run,Run,0.0,13278309978,2025-01-06T06:17:54Z,...,147.1,180.0,True,102.8,95.6,0,1,133094316,a13278309978,_wxpH_zat@Wb@cAtAe@`AyAnBu@xAaAbBQNWBMFWj@YZQB...
185,Morning Run,7656.5,2492,2492,10.0,Run,Run,0.0,14413101200,2025-05-08T08:01:01Z,...,131.3,158.0,True,101.6,93.6,0,0,133094316,a14413101200,ywxpHsyat@gCxDg@bAOTWb@[^O^w@`AKZMLUEEBCBUn@[X...